export const exam_1 = {
    title: "[2022-2023] Cụm trường phía Nam Hưng Yên - Đề thi thử tốt nghiệp THPT môn Tiếng Anh năm 2022-2023",
    date: "07/11/2024",
    result: "0/50",
    duration: "0:19:29",
    participants: 110556, // Updated with the correct participant count from your latest message
    testInfo: {
        examTime: "40 phút",
        sections: 4,
        questions: 40,
        comments: 202,
    },
    part: [10, 20, 30, 40, 50],
    questions: [
        {
            id: 1,
            question:
                "I don't have a smartphone. I can't keep up with my classmates on the online learning course.",
            options: [
                "A. I wish I have a smartphone so that I can keep up with my classmates on the online learning course.",
                "B. If I have a smartphone, I can keep up with my classmates on the online learning course.",
                "C. Unless I have a smartphone, I can't keep up with my classmates on the online learning course.",
                "D. If I had a smartphone, I could keep up with my classmates on the online learning course.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 2,
            question:
                "As soon as James started working, he realized that his decision had not been a good one.",
            options: [
                "A. Since James did not like his new job, he began looking for a better one.",
                "B. No sooner had James begun his new job than he knew his decision was wrong.",
                "C. Had James not begun his new job, he would have gone looking for a better one.",
                "D. Just before James took up his new post, he realized that he was not suited for it.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 3,
            question:
                "As soon as James started working, he realized that his decision had not been a good one.",
            options: [
                "A. Since James did not like his new job, he began looking for a better one.",
                "B. No sooner had James begun his new job than he knew his decision was wrong.",
                "C. Had James not begun his new job, he would have gone looking for a better one.",
                "D. Just before James took up his new post, he realized that he was not suited for it.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 4,
            question:
                "As soon as James started working, he realized that his decision had not been a good one.",
            options: [
                "A. Since James did not like his new job, he began looking for a better one.",
                "B. No sooner had James begun his new job than he knew his decision was wrong.",
                "C. Had James not begun his new job, he would have gone looking for a better one.",
                "D. Just before James took up his new post, he realized that he was not suited for it.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 5,
            question: "The more you practice, the better you become.",
            options: [
                "A. If you practice more, you will become better.",
                "B. Unless you practice, you will not become better.",
                "C. You will become better only if you practice more.",
                "D. Practicing more will make you better.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 6,
            question: "She didn't go to the party because she was ill.",
            options: [
                "A. If she hadn't been ill, she would have gone to the party.",
                "B. She would have gone to the party if she wasn't ill.",
                "C. If she had been ill, she wouldn't have gone to the party.",
                "D. She didn't go to the party unless she was ill.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 7,
            question: "I will call you when I arrive at the airport.",
            options: [
                "A. I will call you as soon as I arrive at the airport.",
                "B. I will call you before I arrive at the airport.",
                "C. I will call you after I arrive at the airport.",
                "D. I will call you while I arrive at the airport.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 8,
            question: "He didn't pass the exam because he didn't study hard.",
            options: [
                "A. If he had studied hard, he would have passed the exam.",
                "B. He would have passed the exam if he studied hard.",
                "C. If he studied hard, he would pass the exam.",
                "D. He didn't pass the exam unless he studied hard.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 9,
            question: "I will go to the beach if it is sunny.",
            options: [
                "A. I will go to the beach unless it is sunny.",
                "B. If it is sunny, I will go to the beach.",
                "C. I will go to the beach even if it is sunny.",
                "D. If it is not sunny, I will go to the beach.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 10,
            question: "She would travel more if she had more money.",
            options: [
                "A. If she had more money, she would travel more.",
                "B. She would travel more unless she had more money.",
                "C. If she has more money, she will travel more.",
                "D. She will travel more if she has more money.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 11,
            question: "If I were you, I would take the job.",
            options: [
                "A. I would take the job if I am you.",
                "B. If I were you, I will take the job.",
                "C. I would take the job unless I were you.",
                "D. If I were you, I would take the job.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 12,
            question: "If it rains, we will cancel the picnic.",
            options: [
                "A. We will cancel the picnic unless it rains.",
                "B. If it rains, we will cancel the picnic.",
                "C. We will cancel the picnic even if it rains.",
                "D. If it does not rain, we will cancel the picnic.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 13,
            question: "If you had told me, I would have helped you.",
            options: [
                "A. I would have helped you if you told me.",
                "B. If you had told me, I would help you.",
                "C. I would have helped you if you had told me.",
                "D. If you told me, I would have helped you.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 14,
            question: "If I had known, I would have acted differently.",
            options: [
                "A. I would have acted differently if I knew.",
                "B. If I had known, I would act differently.",
                "C. I would have acted differently if I had known.",
                "D. If I knew, I would have acted differently.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 15,
            question: "If you practice regularly, you will improve.",
            options: [
                "A. You will improve if you practice regularly.",
                "B. If you practice regularly, you will improve.",
                "C. You will improve unless you practice regularly.",
                "D. If you do not practice regularly, you will improve.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 16,
            question: "If I had more time, I would learn another language.",
            options: [
                "A. I would learn another language if I had more time.",
                "B. If I have more time, I would learn another language.",
                "C. I would learn another language unless I had more time.",
                "D. If I had more time, I will learn another language.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 17,
            question: "If you eat too much, you will gain weight.",
            options: [
                "A. You will gain weight if you eat too much.",
                "B. If you eat too much, you will gain weight.",
                "C. You will gain weight unless you eat too much.",
                "D. If you do not eat too much, you will gain weight.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 18,
            question: "If I were rich, I would travel the world.",
            options: [
                "A. I would travel the world if I am rich.",
                "B. If I were rich, I will travel the world.",
                "C. I would travel the world unless I were rich.",
                "D. If I were rich, I would travel the world.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 19,
            question: "If you study hard, you will succeed.",
            options: [
                "A. You will succeed if you study hard.",
                "B. If you study hard, you will succeed.",
                "C. You will succeed unless you study hard.",
                "D. If you do not study hard, you will succeed.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 20,
            question: "If I had a car, I would drive to work.",
            options: [
                "A. I would drive to work if I had a car.",
                "B. If I have a car, I would drive to work.",
                "C. I would drive to work unless I had a car.",
                "D. If I had a car, I will drive to work.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 21,
            question:
                "If I had known about the meeting, I would have attended.",
            options: [
                "A. I would have attended the meeting if I knew about it.",
                "B. If I had known about the meeting, I would attend.",
                "C. I would have attended the meeting if I had known about it.",
                "D. If I knew about the meeting, I would have attended.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 22,
            question: "If you had worked harder, you would have succeeded.",
            options: [
                "A. You would have succeeded if you worked harder.",
                "B. If you had worked harder, you would succeed.",
                "C. You would have succeeded if you had worked harder.",
                "D. If you worked harder, you would have succeeded.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 23,
            question: "If I had more money, I would buy a new car.",
            options: [
                "A. I would buy a new car if I had more money.",
                "B. If I have more money, I would buy a new car.",
                "C. I would buy a new car unless I had more money.",
                "D. If I had more money, I will buy a new car.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 24,
            question: "If you had called me, I would have come.",
            options: [
                "A. I would have come if you called me.",
                "B. If you had called me, I would come.",
                "C. I would have come if you had called me.",
                "D. If you called me, I would have come.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 25,
            question: "If I were you, I would apologize.",
            options: [
                "A. I would apologize if I am you.",
                "B. If I were you, I will apologize.",
                "C. I would apologize unless I were you.",
                "D. If I were you, I would apologize.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 26,
            question: "If it rains tomorrow, we will stay home.",
            options: [
                "A. We will stay home unless it rains tomorrow.",
                "B. If it rains tomorrow, we will stay home.",
                "C. We will stay home even if it rains tomorrow.",
                "D. If it does not rain tomorrow, we will stay home.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 27,
            question: "If you had studied, you would have passed the exam.",
            options: [
                "A. You would have passed the exam if you studied.",
                "B. If you had studied, you would pass the exam.",
                "C. You would have passed the exam if you had studied.",
                "D. If you studied, you would have passed the exam.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 28,
            question: "If I had known you were coming, I would have waited.",
            options: [
                "A. I would have waited if I knew you were coming.",
                "B. If I had known you were coming, I would wait.",
                "C. I would have waited if I had known you were coming.",
                "D. If I knew you were coming, I would have waited.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 29,
            question: "If you practice more, you will improve.",
            options: [
                "A. You will improve if you practice more.",
                "B. If you practice more, you will improve.",
                "C. You will improve unless you practice more.",
                "D. If you do not practice more, you will improve.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 30,
            question: "If I had a chance, I would travel to Japan.",
            options: [
                "A. I would travel to Japan if I had a chance.",
                "B. If I have a chance, I would travel to Japan.",
                "C. I would travel to Japan unless I had a chance.",
                "D. If I had a chance, I will travel to Japan.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 31,
            question: "If you had told me earlier, I could have helped.",
            options: [
                "A. I could have helped if you told me earlier.",
                "B. If you had told me earlier, I could help.",
                "C. I could have helped if you had told me earlier.",
                "D. If you told me earlier, I could have helped.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 32,
            question: "If I were in your position, I would take the offer.",
            options: [
                "A. I would take the offer if I am in your position.",
                "B. If I were in your position, I will take the offer.",
                "C. I would take the offer unless I were in your position.",
                "D. If I were in your position, I would take the offer.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 33,
            question: "If it doesn't rain, we will go for a walk.",
            options: [
                "A. We will go for a walk unless it doesn't rain.",
                "B. If it doesn't rain, we will go for a walk.",
                "C. We will go for a walk even if it doesn't rain.",
                "D. If it rains, we will go for a walk.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 34,
            question: "If you had listened to me, you wouldn't be in trouble.",
            options: [
                "A. You wouldn't be in trouble if you listened to me.",
                "B. If you had listened to me, you wouldn't be in trouble.",
                "C. You wouldn't be in trouble if you had listened to me.",
                "D. If you listened to me, you wouldn't be in trouble.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 35,
            question: "If I had more time, I would read more books.",
            options: [
                "A. I would read more books if I had more time.",
                "B. If I have more time, I would read more books.",
                "C. I would read more books unless I had more time.",
                "D. If I had more time, I will read more books.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 36,
            question: "If you had been there, you would have seen it.",
            options: [
                "A. You would have seen it if you were there.",
                "B. If you had been there, you would see it.",
                "C. You would have seen it if you had been there.",
                "D. If you were there, you would have seen it.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 37,
            question: "If I were you, I would take a break.",
            options: [
                "A. I would take a break if I am you.",
                "B. If I were you, I will take a break.",
                "C. I would take a break unless I were you.",
                "D. If I were you, I would take a break.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 38,
            question: "If it snows, we will build a snowman.",
            options: [
                "A. We will build a snowman unless it snows.",
                "B. If it snows, we will build a snowman.",
                "C. We will build a snowman even if it snows.",
                "D. If it does not snow, we will build a snowman.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 39,
            question: "If you had asked, I would have helped.",
            options: [
                "A. I would have helped if you asked.",
                "B. If you had asked, I would help.",
                "C. I would have helped if you had asked.",
                "D. If you asked, I would have helped.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 40,
            question: "If I had known, I would have told you.",
            options: [
                "A. I would have told you if I knew.",
                "B. If I had known, I would tell you.",
                "C. I would have told you if I had known.",
                "D. If I knew, I would have told you.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 41,
            question: "If you practice daily, you will get better.",
            options: [
                "A. You will get better if you practice daily.",
                "B. If you practice daily, you will get better.",
                "C. You will get better unless you practice daily.",
                "D. If you do not practice daily, you will get better.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 42,
            question: "If I had a bicycle, I would ride to school.",
            options: [
                "A. I would ride to school if I had a bicycle.",
                "B. If I have a bicycle, I would ride to school.",
                "C. I would ride to school unless I had a bicycle.",
                "D. If I had a bicycle, I will ride to school.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 43,
            question: "If you had been careful, you wouldn't have fallen.",
            options: [
                "A. You wouldn't have fallen if you were careful.",
                "B. If you had been careful, you wouldn't fall.",
                "C. You wouldn't have fallen if you had been careful.",
                "D. If you were careful, you wouldn't have fallen.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 44,
            question: "If I were rich, I would buy a mansion.",
            options: [
                "A. I would buy a mansion if I am rich.",
                "B. If I were rich, I will buy a mansion.",
                "C. I would buy a mansion unless I were rich.",
                "D. If I were rich, I would buy a mansion.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 45,
            question: "If it doesn't snow, we will go hiking.",
            options: [
                "A. We will go hiking unless it doesn't snow.",
                "B. If it doesn't snow, we will go hiking.",
                "C. We will go hiking even if it doesn't snow.",
                "D. If it snows, we will go hiking.",
            ],
            answer: "A",
            correct: "B",
        },
        {
            id: 46,
            question: "If you had told me, I would have come.",
            options: [
                "A. I would have come if you told me.",
                "B. If you had told me, I would come.",
                "C. I would have come if you had told me.",
                "D. If you told me, I would have come.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 47,
            question: "If I had more time, I would visit my family.",
            options: [
                "A. I would visit my family if I had more time.",
                "B. If I have more time, I would visit my family.",
                "C. I would visit my family unless I had more time.",
                "D. If I had more time, I will visit my family.",
            ],
            answer: "A",
            correct: "A",
        },
        {
            id: 48,
            question: "If you had been there, you would have known.",
            options: [
                "A. You would have known if you were there.",
                "B. If you had been there, you would know.",
                "C. You would have known if you had been there.",
                "D. If you were there, you would have known.",
            ],
            answer: "A",
            correct: "C",
        },
        {
            id: 49,
            question: "If I were you, I would take the chance.",
            options: [
                "A. I would take the chance if I am you.",
                "B. If I were you, I will take the chance.",
                "C. I would take the chance unless I were you.",
                "D. If I were you, I would take the chance.",
            ],
            answer: "A",
            correct: "D",
        },
        {
            id: 50,
            question: "If it rains, we will stay indoors.",
            options: [
                "A. We will stay indoors unless it rains.",
                "B. If it rains, we will stay indoors.",
                "C. We will stay indoors even if it rains.",
                "D. If it does not rain, we will stay indoors.",
            ],
            answer: "A",
            correct: "B",
        },
    ],
};
